version: '3.8'
services:

  order-service:
    image: koon0121/springboot-order
    ports:
      - "8803:8803"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3307/octest
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - springboot-order
      
networks:
  springboot-order: