apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: host.docker.internal
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306